# Generated by Django 3.2.5 on 2021-08-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link above To Read Blog Post...', max_length=255),
        ),
    ]
